name: Tweet Bot

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: pip install -r requirements.txt

    - name: Ejecutar bot
      env:
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      run: python bot/main.py
