name: Tweet bot

on:
  schedule:
    - cron: '0 */6 * * *'  # cada 6 horas (en UTC)
  workflow_dispatch:        # permite correrlo a mano

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          python bot/main.py
